const image=(name,alt,extra='')=>`<img src="assets/experiential/${name}.webp" srcset="assets/experiential/${name}-mobile.webp 800w, assets/experiential/${name}.webp 1440w" sizes="(max-width:700px) 100vw, 65vw" alt="${alt}" width="1440" height="1080" loading="lazy" decoding="async" ${extra}>`;
const room=(id,alt)=>`<img src="assets/experimental-v2/${id}.webp" alt="${alt}" width="1440" height="1080" loading="lazy" decoding="async">`;
export const content=`
<section class="x-intro x-section" id="after-film"><div class="x-intro-copy" data-reveal><span class="x-overline">DESIGN, BEYOND THE DRAWING</span><h2>Your future home.<br><em>Already within reach.</em></h2><p>VR brings you inside. AI opens up possibilities.<br>Vivid brings it all back to you.</p></div><div class="x-model" data-x-parallax>${image('digital-residence','Architectural concept model transitioning from gold wireframe to a furnished home')}<div class="x-orbit orbit-one"></div><div class="x-orbit orbit-two"></div><span class="x-model-point point-one"></span><span class="x-model-point point-two"></span></div><div class="x-intro-bottom"><span>Imagine it. Explore it. Make it yours.</span><a href="#x-vr" class="x-circle" aria-label="Explore virtual reality">↓</a></div></section>

<section class="x-vr x-section" id="x-vr"><div class="x-section-head" data-reveal><span class="x-overline">VIRTUAL REALITY</span><h2>Don't just picture it.<br><em>Be there.</em></h2><p>Understand the scale. Feel the flow. Stand in the spaces you’re about to call home—before construction begins.</p></div><div class="x-vr-layout"><div class="x-vr-photo" data-reveal>${image('vr-session','A client exploring a residential interior through a VR headset')}<div class="x-viewfinder" aria-hidden="true"><i></i><i></i><i></i><i></i><span>+</span></div></div><div class="x-vr-copy" data-reveal><h3>A new kind<br>of first visit.</h3><p>Walk from the entrance to the kitchen. Look up at the volume above you. Talk through the details while they’re right in front of you.</p><div class="x-benefit"><span>↗</span><div><h4>Understand your space</h4><p>See room relationships from a human perspective.</p></div></div><div class="x-benefit"><span>↗</span><div><h4>Decide with context</h4><p>Explore the choices as part of the whole home.</p></div></div><button class="x-button" data-back-tour>Step into the walkthrough <span>↗</span></button></div></div></section>

<section class="x-explore x-section" id="x-explore"><div class="x-section-head" data-reveal><span class="x-overline">A SMALL TASTE OF BEING THERE</span><h2>Follow your<br><em>point of view.</em></h2><p>A real space. Real depth. Trace the living room in gold, rotate the structure, and step inside.</p></div><div class="room3d-stage" id="room3d-stage"><canvas tabindex="0" aria-label="Interactive 3D model of the Mashini living room. Activate Explore in 3D to drag and pinch, or use the view buttons below. Arrow keys rotate, Escape leaves exploration."></canvas><div class="room3d-status" role="status">Preparing your space…</div><div class="room3d-corners" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="room3d-overlay"><span class="room3d-hint">A living space, from every angle</span><span class="room3d-depth" aria-hidden="true">↔</span></div></div><div class="room3d-controls"><button id="room3d-explore" class="x-button" aria-pressed="false" disabled>Explore in 3D</button><div class="room3d-view-buttons" role="group" aria-label="Choose a 3D room view"><button data-room3d-view="orbit" aria-pressed="true" disabled>Overview</button><button data-room3d-view="inside" aria-pressed="false" disabled>Step inside</button><button id="room3d-reset" aria-label="Reset the 3D view" disabled>↺</button></div></div><p class="room3d-scroll-note">Drag to rotate. Pinch to zoom. Tap Done to continue scrolling.</p></section>

<section class="x-ai x-section" id="x-ai"><div class="x-section-head" data-reveal><span class="x-overline">AI-ASSISTED EXPLORATION</span><h2>More possibilities.<br><em>More you.</em></h2><p>Ideas become something you can react to. Explore atmosphere, materials and detail with AI-assisted imagery, then refine the direction with your designer.</p></div><div class="x-ai-board" data-reveal><div class="x-ai-image">${room('08-living-window','A bright living room design with warm natural light')}<div class="x-scan" aria-hidden="true"></div><div class="x-ai-caption"><span id="x-ai-tag">LIGHT & OPEN</span><h3 id="x-ai-title">Room to breathe.</h3></div></div><div class="x-ai-panel"><span class="x-overline">WHAT FEELS LIKE YOU?</span><p>Start with a feeling.<br>Find a direction.</p><div class="x-ai-choices" role="group" aria-label="Explore a design direction"><button data-direction="0" aria-pressed="true"><span class="x-choice-mark">✦</span><span>Light & open<small>Daylight. Softness. Space.</small></span><i>↗</i></button><button data-direction="1" aria-pressed="false"><span class="x-choice-mark">◈</span><span>Warm & grounded<small>Oak. Texture. Quiet focus.</small></span><i>↗</i></button><button data-direction="2" aria-pressed="false"><span class="x-choice-mark">◇</span><span>Calm & considered<small>Linen. Stillness. Simplicity.</small></span><i>↗</i></button></div><div class="x-ai-note"><i></i>AI opens the conversation.<br>Your designer shapes the answer.</div></div></div></section>

<section class="x-dialogue x-section" data-atmosphere="warm"><div class="x-section-head" data-reveal><span class="x-overline">TECHNOLOGY WITH A HUMAN TOUCH</span><h2>Your reaction<br><em>is part of the design.</em></h2></div><div class="x-dialogue-layout"><div class="x-dialogue-photo" data-reveal>${image('design-dialogue','Client and designer discussing a room image alongside stone, oak, linen and brass samples')}<span class="x-photo-line" aria-hidden="true"></span><div class="atmosphere-glow" aria-hidden="true"></div><div class="atmosphere-beam" aria-hidden="true"></div><div class="atmosphere-rings" aria-hidden="true"><i></i><i></i><i></i></div><span class="atmosphere-caption">A WARMER PERSPECTIVE</span></div><div class="x-feedback" data-reveal><h3>“I love this.<br>Could it feel warmer?”</h3><p>That’s where the next version begins. See a direction, share what matters, and work with Vivid to bring the details into focus.</p><div class="x-feedback-choices" role="group" aria-label="Try a design conversation"><button data-feedback="warm" aria-pressed="true">More warmth</button><button data-feedback="light" aria-pressed="false">More light</button><button data-feedback="quiet" aria-pressed="false">More calm</button></div><div class="x-response" aria-live="polite"><span>THE CONVERSATION CONTINUES</span><p id="x-response-copy">Explore richer timber, tactile fabrics and a softer lighting atmosphere.</p></div></div></div></section>

<section class="x-material-play x-section" id="x-material-play"><div class="x-section-head" data-reveal><span class="x-overline">A FEELING YOU CAN TURN OVER</span><h2>Same form.<br><em>Different feeling.</em></h2><p>Change the finish. Move the light. Discover how a material changes everything.</p></div><div class="material-play-layout"><div class="material-play-stage" id="material-play-stage"><canvas tabindex="0" aria-label="Interactive material sculpture. Drag sideways or use arrow keys to turn it."></canvas><span class="material-play-status" role="status">Shaping a possibility…</span><span class="material-play-hint">DRAG SIDEWAYS TO TURN</span></div><div class="material-play-panel"><div class="finish-options" role="group" aria-label="Choose a material finish"><button data-finish="brass" aria-pressed="true"><i></i>Brass</button><button data-finish="stone" aria-pressed="false"><i></i>Stone</button><button data-finish="ink" aria-pressed="false"><i></i>Dark metal</button></div><div class="finish-description" aria-live="polite"><h3 id="finish-title">A little brilliance.</h3><p id="finish-copy">Brushed brass catches the light. Watch its highlights move as you turn the sculpture.</p></div><label class="finish-light-control" for="finish-light"><span>Move the light <i aria-hidden="true">☀</i></span><input id="finish-light" type="range" min="0" max="100" value="65"><span class="finish-light-labels"><small>LEFT</small><small>RIGHT</small></span></label></div></div></section>

<section class="x-process x-section"><div class="x-section-head" data-reveal><span class="x-overline">ONE CONNECTED EXPERIENCE</span><h2>From your first idea.<br><em>To a clearer yes.</em></h2></div><div class="x-process-list"><details open data-reveal><summary><span>Tell us what home feels like.</span><i>+</i></summary><p>Your routines, your references, your ambitions. The experience starts with listening.</p></details><details data-reveal><summary><span>See the possibilities take shape.</span><i>+</i></summary><p>AI-assisted visual exploration makes early ideas tangible, so you can compare directions and describe what resonates.</p></details><details data-reveal><summary><span>Step inside your design.</span><i>+</i></summary><p>VR and architectural walkthroughs put spaces into context. Explore how rooms connect and discuss what you would change.</p></details><details data-reveal><summary><span>Refine it, together.</span><i>+</i></summary><p>Bring your feedback into the next design conversation. Materials, proportions and atmosphere become considered decisions.</p></details></div></section>

<section class="x-finale x-section"><div class="x-finale-orbit" aria-hidden="true"><i></i><i></i><i></i><b>V</b></div><div data-reveal><span class="x-overline">VIVID DESIGN STUDIO</span><h2>The future of design<br>is <em>personal.</em></h2><p>Let's make yours something you can feel.</p><a class="x-button" href="https://www.vividdesignstudio.com/contact">Experience your possibilities <span>↗</span></a></div><footer><a href="https://www.vividdesignstudio.com/">VIVID DESIGN STUDIO</a><a href="mailto:evander@vividdesignstudio.com">Let's talk ↗</a></footer></section>`;

export function initExperiential(){
 const atmosphereButtons=document.querySelector('.x-feedback-choices');
 document.querySelector('.x-dialogue-photo').append(atmosphereButtons);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const host=document.getElementById('room3d-stage');
 const modelObserver=new IntersectionObserver(async ([entry])=>{if(!entry.isIntersecting)return;modelObserver.disconnect();try{const {initRoomViewer}=await import('./room-viewer.js?v=3');await initRoomViewer(host);}catch(e){host.querySelector('.room3d-status').textContent='The 3D view could not load. Please reload to try again.';}},{rootMargin:'400px'});modelObserver.observe(host);
 const directions=[['08-living-window','LIGHT & OPEN','Room to breathe.','A light and open living room'],['02-office-library','WARM & GROUNDED','A quieter kind of focus.','A warm oak office and library'],['24-bedroom','CALM & CONSIDERED','Let the world slow down.','A calm bedroom with natural linen']];
 let selection=0;
 document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=async()=>{const n=Number(b.dataset.direction),d=directions[n];selection=n;const im=document.querySelector('.x-ai-image img');const next=new Image();next.src=`assets/experimental-v2/${d[0]}.webp`;try{await next.decode()}catch{}if(selection!==n)return;im.src=next.src;im.alt=d[3];document.getElementById('x-ai-tag').textContent=d[1];document.getElementById('x-ai-title').textContent=d[2];document.querySelectorAll('[data-direction]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const board=document.querySelector('.x-ai-board');board.classList.remove('changed');void board.offsetWidth;board.classList.add('changed');});
 const responses={warm:'Explore richer timber, tactile fabrics and a softer lighting atmosphere.',light:'Explore lighter finishes, window treatments and how daylight can travel through the space.',quiet:'Explore a restrained palette, softer textures and room for the details that matter.'};
 document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{document.getElementById('x-response-copy').textContent=responses[b.dataset.feedback];const atmosphere=document.querySelector('.x-dialogue');atmosphere.dataset.atmosphere=b.dataset.feedback;atmosphere.querySelector('.atmosphere-caption').textContent={warm:'A WARMER PERSPECTIVE',light:'LET THE LIGHT IN',quiet:'A MOMENT TO EXHALE'}[b.dataset.feedback];atmosphere.classList.remove('atmosphere-changed');void atmosphere.offsetWidth;atmosphere.classList.add('atmosphere-changed');document.querySelectorAll('[data-feedback]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
 const specimen=document.getElementById('material-play-stage');const specimenObserver=new IntersectionObserver(async ([e])=>{if(!e.isIntersecting)return;specimenObserver.disconnect();try{const {initMaterialPlay}=await import('./material-play.js?v=1');await initMaterialPlay(specimen);}catch{specimen.querySelector('.material-play-status').textContent='The material preview could not load. Please reload.';}},{rootMargin:'300px'});specimenObserver.observe(specimen);
 const panels=[...document.querySelectorAll('.x-process details')];panels.forEach(d=>d.addEventListener('toggle',()=>{if(d.open)panels.forEach(other=>{if(other!==d)other.open=false})}));
 let raf=0;const model=document.querySelector('.x-model');function paint(){raf=0;if(reduced.matches)return;const r=model.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){model.style.setProperty('--float',`${Math.max(-28,Math.min(28,(r.top-innerHeight*.3)*-.055))}px`);model.style.setProperty('--model-turn',`${Math.max(-7,Math.min(7,(r.top-innerHeight*.3)*.015))}deg`)}document.querySelectorAll('.x-vr-photo,.x-dialogue-photo').forEach(el=>{const box=el.getBoundingClientRect();if(box.bottom>0&&box.top<innerHeight){const p=Math.max(0,Math.min(1,(innerHeight-box.top)/(innerHeight+box.height)));el.style.setProperty('--reveal',p);}})}
 addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(paint)},{passive:true});
 window.__experientialDebug={ready:true};
}
