import {initPerspectiveCube} from './perspective-cube.js?v=1';
const css=document.createElement('link');css.rel='stylesheet';css.href='./experimental.css?v=cube-2';document.head.append(css);
import {photographs} from './experimental-media.js?v=unique-2';
let photoIndex=0;
const photo=(roomKey,oldAlt='',classes='')=>{
 const shot=photographs[photoIndex++];
 if(!shot)throw new Error('Missing Experimental still mapping');
 return `<img class="${classes}" src="assets/experimental-v2/${shot.id}.webp" srcset="assets/experimental-v2/${shot.id}-mobile.webp 800w, assets/experimental-v2/${shot.id}.webp 1440w" sizes="(max-width: 600px) 100vw, (max-width: 1000px) 70vw, 900px" data-image-id="${shot.id}" style="object-position:${shot.focus}" alt="${shot.alt}" width="1440" height="1080" loading="lazy" decoding="async" draggable="false">`;
};
const index=(n,label)=>`<div class="exp-kicker"><span>${String(n).padStart(2,'0')} / 10</span><span>${label}</span><i>V / LAB</i></div>`;
const note=text=>`<div class="exp-note"><span class="exp-dot"></span>${text}</div>`;
export const content=`
<div class="exp-nav"><button id="exp-index-toggle" aria-expanded="false" aria-controls="exp-index">Explore spaces <span>↗</span></button><span id="exp-current">01 / 10</span><nav id="exp-index" hidden aria-label="Jump to an experiment">${['Room to feel','Favorite places','Open a little wonder','Chase the light','Plan to possibility','Turn the room','A closer connection','Follow a material','Collect a feeling','Your own perspective'].map((label,i)=>`<a href="#${i===0?'after-film':`experiment-${i+1}`}"><span>${String(i+1).padStart(2,'0')}</span>${label}</a>`).join('')}</nav></div>

<section class="experiment exp-cloud exp-scroll" id="after-film" data-exp="1" data-scroll-effect="cloud"><div class="exp-pin">${index(1,'SPACE, WITH FEELING')}<div class="cloud-title"><h2>Space to live.<br><em>Room to feel.</em></h2><p>Some places just move you.</p></div><div class="cloud-photos"><button class="cloud-photo cloud-one" aria-label="Bring the living room forward">${photo('living','A sunlit living room')}<span>LIGHT / 01</span></button><button class="cloud-photo cloud-two" aria-label="Bring the office forward">${photo('office','A warm wood office')}<span>STILLNESS / 02</span></button><button class="cloud-photo cloud-three" aria-label="Bring the kitchen forward">${photo('kitchen','The connected kitchen and dining room')}<span>TOGETHER / 03</span></button></div>${note('Scroll to drift. Tap a photograph to bring it closer.')}</div></section>

<section class="experiment exp-favorites" id="experiment-2" data-exp="2">${index(2,'STAY A LITTLE LONGER')}<h2>Find your<br><em>favorite place.</em></h2><p class="exp-sub">Tap a room. Make space for it.</p><div class="exp-vertical-rooms">${[['living','Gather','Room to be together.'],['kitchen','Discover','The heart of the home.'],['office','Retreat','Your quiet retreat.']].map(([image,name,copy],i)=>`<article class="exp-room ${i===0?'open':''}"><div class="exp-room-image">${photo(image,copy)}</div><button class="exp-room-toggle" aria-expanded="${i===0}" aria-controls="exp-room-copy-${i}"><span>0${i+1}</span><h3>${name}</h3><i aria-hidden="true">${i===0?'−':'+'}</i></button><div class="exp-room-copy" id="exp-room-copy-${i}"><p>${copy}</p><button class="save-room" data-save="${image}" aria-pressed="false">Save this feeling <span>♡</span></button></div></article>`).join('')}</div></section>

<section class="experiment exp-door exp-scroll" id="experiment-3" data-exp="3" data-scroll-effect="door"><div class="exp-pin">${index(3,'THE ART OF THE REVEAL')}<h2>Open a little<br><em>wonder.</em></h2><div class="door-theatre">${photo('wine-cellar','The illuminated wine cellar','door-behind')}<div class="door-room-shade"></div><div class="door-leaf door-left"><div></div><i></i></div><div class="door-leaf door-right"><div></div><i></i></div><div class="door-frame"></div><span class="door-room-name">SOMETHING WORTH DISCOVERING.</span></div><button id="exp-door-toggle" class="exp-pill" aria-pressed="false">Open the doors <span>↗</span></button>${note('Scroll to open the space. Or tap the button.')}</div></section>

<section class="experiment exp-light" id="experiment-4" data-exp="4">${index(4,'A LITTLE CHANGE IN ATMOSPHERE')}<div class="light-heading"><h2>Chase<br><em>the light.</em></h2><span id="light-mood">Soft daylight</span></div><div class="light-photo">${photo('living','Light in the living room')}<div class="light-warmth"></div><div class="light-beam"></div><span class="light-photo-caption">SAME SPACE. A DIFFERENT FEELING.</span></div><div class="light-dial"><div class="sun-path" aria-hidden="true"><span>☀</span></div><label for="light-control">Move the sun</label><input id="light-control" aria-label="Change the light study from soft to golden" type="range" min="0" max="100" value="15"><div class="light-endpoints"><span>SOFT</span><span>WARM</span><span>GOLDEN</span></div></div><p class="exp-small">An atmospheric light study. Slide to explore.</p></section>

<section class="experiment exp-plan" id="experiment-5" data-exp="5">${index(5,'FROM A LINE TO A LIFE')}<h2>Possibility,<br><em>at your fingertips.</em></h2><p class="exp-sub">Touch the drawing. Find the home within.</p><div class="reveal-stage" id="reveal-stage" aria-label="Touch the plan to reveal the furnished home"><canvas id="blueprint-canvas" role="img" aria-label="Conceptual house plan line drawing"></canvas><img id="built-plan" src="assets/experimental-v2/09-plan.webp" data-image-id="09-plan" alt="Furnished top-down concept of the home" width="1440" height="1080" loading="lazy" draggable="false"><div class="blueprint-grid"></div><div class="reveal-lens" aria-hidden="true"><span>IMAGINE</span><i></i></div><div class="plan-loading" role="status">Preparing the plan…</div></div><div class="exp-plan-controls"><label>Move the reveal<input id="reveal-position" aria-label="Move the reveal lens left or right" type="range" min="0" max="100" value="55"></label><button id="reveal-all" class="exp-pill" aria-pressed="false">Reveal whole home <span>↗</span></button></div><span class="exp-small">MASHINI / CONCEPT STUDY</span></section>

<section class="experiment exp-turn" id="experiment-6" data-exp="6">${index(6,'THERE’S ALWAYS ANOTHER ANGLE')}<h2>A different<br><em>perspective.</em></h2><p class="exp-sub">Drag to spin. Tilt to discover.</p><div class="cube-stage"><div class="cube-shadow"></div><div class="room-cube">${['living','kitchen','office','wine-cellar'].map((name,i)=>`<div class="cube-face cube-face-${i}">${photo(name,`${['Covered terrace','Kitchen','Bathroom','Upper gallery'][i]} perspective`)}<span>${['BREATHE','DISCOVER','UNWIND','WANDER'][i]}</span></div>`).join('')}</div><span class="cube-floor-label">VIVID / FOUR WAYS TO FEEL AT HOME</span></div><div class="cube-controls" role="group" aria-label="Turn to a room">${['Terrace','Kitchen','Bath','Gallery'].map((label,i)=>`<button data-cube="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${label}</button>`).join('')}</div><button id="cube-reset" class="cube-reset">Reset view ↺</button><p class="cube-touch-hint">Drag the cube in any direction. Scroll outside it to continue.</p></section>

<section class="experiment exp-iris exp-scroll" id="experiment-7" data-exp="7" data-scroll-effect="iris"><div class="exp-pin">${index(7,'A CLOSER CONNECTION')}<div class="iris-copy"><h2>A little closer.<br><em>There you are.</em></h2><p>Let the rest of the world fall away.</p></div><div class="iris-window">${photo('office','A quiet office overlooking the chandelier')}<div class="iris-shade"></div><span>A PLACE OF YOUR OWN.</span></div><button id="iris-toggle" class="exp-pill" aria-pressed="false">Step inside <span>↗</span></button>${note('Keep scrolling. Let the room surround you.')}</div></section>

<section class="experiment exp-material" id="experiment-8" data-exp="8">${index(8,'FOLLOW WHAT MOVES YOU')}<h2>Feel it<br><em>in the details.</em></h2><div class="material-arch"><div class="material-photo">${photo('office','Warm timber in the home','material-image active')}${photo('living','Soft stone and upholstery','material-image')}${photo('wine-cellar','Dark metal framed glazing','material-image')}</div><span class="material-index">01 / 03</span><div class="material-caption"><span id="material-name">Warm timber.</span><p id="material-copy">A little warmth goes a long way.</p></div></div><div class="material-swatches" role="group" aria-label="Explore a material"><button data-material="0" aria-pressed="true"><i class="swatch-wood"></i><span>Timber</span></button><button data-material="1" aria-pressed="false"><i class="swatch-stone"></i><span>Stone</span></button><button data-material="2" aria-pressed="false"><i class="swatch-metal"></i><span>Metal</span></button></div>${note('Tap a material. Follow its feeling through the home.')}</section>

<section class="experiment exp-collection" id="experiment-9" data-exp="9">${index(9,'SOME SPACES STAY WITH YOU')}<h2>Collect<br><em>a feeling.</em></h2><p class="exp-sub">Keep scrolling. Save the ones that speak to you.</p><div class="collection-stack">${[['kitchen','Everyday, considered.','Beauty in the quieter corners.'],['office','A quiet moment.','Somewhere for your next idea.'],['living','A softer start.','Wake up slowly. Stay a little.']].map(([name,title,copy],i)=>`<article class="collection-card" style="--card-index:${i}">${photo(name,title)}<span class="collection-number">0${i+1} / A MOMENT IN THE HOME</span><div><h3>${title}</h3><p>${copy}</p><button class="save-room" data-save="${name}" aria-pressed="false">Save this feeling <span>♡</span></button></div></article>`).join('')}</div></section>

<section class="experiment exp-edit" id="experiment-10" data-exp="10">${index(10,'MAKE IT PERSONAL')}<h2>Your home.<br><em>Your kind of feeling.</em></h2><p id="edit-intro" class="exp-sub">A few possibilities to play with. Tap a photograph.</p><div class="edit-board">${['living','kitchen','office'].map((name,i)=>`<button class="edit-photo ${i===1?'on-top':''}" data-edit="${name}" aria-label="Bring ${name==='living'?'courtyard':name} to the front" aria-pressed="${i===1}">${photo(name,`${name} moodboard photograph`)}<span>${['ARRIVAL','DISCOVERY','STILLNESS'][i]}</span><i class="edit-saved" aria-hidden="true">♥</i></button>`).join('')}</div><div class="edit-summary" role="status" id="edit-summary">YOUR PERSPECTIVE STARTS HERE.</div><button id="shuffle-board" class="exp-pill">Remix the moodboard <span>⤨</span></button><a class="edit-cta" href="https://www.vividdesignstudio.com/contact">Let’s make room for you <span>↗</span></a><button class="edit-replay" data-back-tour>Take the walkthrough again ↑</button><footer class="exp-footer"><span>VIVID DESIGN STUDIO</span><a href="mailto:evander@vividdesignstudio.com">Let’s talk ↗</a></footer></section>
`;

export function initExperimental(){
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const experiments=[...document.querySelectorAll('.experiment')];
 let raf=0;const clamp=x=>Math.max(0,Math.min(1,x));
 const nav=document.querySelector('.exp-nav'),indexButton=document.getElementById('exp-index-toggle'),indexMenu=document.getElementById('exp-index');
 indexButton.onclick=()=>{const open=indexMenu.hidden;indexMenu.hidden=!open;indexButton.setAttribute('aria-expanded',String(open))};
 indexMenu.querySelectorAll('a').forEach(a=>a.onclick=()=>{indexMenu.hidden=true;indexButton.setAttribute('aria-expanded','false')});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){indexMenu.hidden=true;indexButton.setAttribute('aria-expanded','false')}});
 function paint(){
  raf=0;const showNav=scrollY>innerHeight*.8;nav.classList.toggle('visible',showNav);nav.inert=!showNav;
  const inset=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--review-height'));
  let current=1;
  for(const section of experiments){
   const rect=section.getBoundingClientRect();if(rect.top<innerHeight*.55)current=Number(section.dataset.exp);
   if(rect.bottom<0||rect.top>innerHeight)continue;
   if(section.matches('.exp-scroll')&&!reduced.matches){const progress=clamp((-rect.top+inset)/(rect.height-innerHeight+inset));section.style.setProperty('--p',progress.toFixed(4));}
  }
  document.getElementById('exp-current').textContent=`${String(current).padStart(2,'0')} / 10`;
  window.__experimentalDebug={sections:experiments.length,current,reduced:reduced.matches};
 }
 window.addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(paint)},{passive:true});window.addEventListener('resize',paint,{passive:true});paint();
 document.querySelectorAll('.cloud-photo').forEach(button=>button.onclick=()=>{const was=button.classList.contains('closer');document.querySelectorAll('.cloud-photo').forEach(el=>{el.classList.remove('closer');el.setAttribute('aria-pressed','false')});if(!was){button.classList.add('closer');button.setAttribute('aria-pressed','true')}});
 document.querySelectorAll('.exp-room-toggle').forEach(button=>button.onclick=()=>{
  document.querySelectorAll('.exp-room').forEach(room=>{const open=room.contains(button);room.classList.toggle('open',open);const b=room.querySelector('.exp-room-toggle');b.setAttribute('aria-expanded',String(open));b.querySelector('i').textContent=open?'−':'+';room.querySelector('.exp-room-copy').inert=!open;});
 });
 document.querySelectorAll('.exp-room:not(.open) .exp-room-copy').forEach(el=>el.inert=true);
 function toggleStage(buttonId,sectionClass){const b=document.getElementById(buttonId);b.onclick=()=>{const active=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(active));const section=document.querySelector(sectionClass);section.classList.add('manual');section.classList.toggle('force-open',active);b.innerHTML=`${buttonId==='exp-door-toggle'?(active?'Close the doors':'Open the doors'):(active?'Step back':'Step inside')} <span>${active?'↙':'↗'}</span>`;};}
 toggleStage('exp-door-toggle','.exp-door');toggleStage('iris-toggle','.exp-iris');
 const light=document.querySelector('.exp-light');document.getElementById('light-control').oninput=e=>{const p=Number(e.target.value)/100;light.style.setProperty('--light',p);document.getElementById('light-mood').textContent=p<.34?'Soft daylight':p<.7?'A little warmer':'Golden atmosphere';};
 initPerspectiveCube();
 const palettes=[['Warm timber.','A little warmth goes a long way.','#cbbba4','#2b352b'],['Soft stone.','Quiet, grounded, beautifully simple.','#e9e5da','#32362e'],['Dark metal.','A little contrast. A lot of character.','#202d2c','#eef1e5']];
 document.querySelectorAll('[data-material]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.material),section=document.querySelector('.exp-material');section.style.setProperty('--material-bg',palettes[i][2]);section.style.setProperty('--material-ink',palettes[i][3]);document.getElementById('material-name').textContent=palettes[i][0];document.getElementById('material-copy').textContent=palettes[i][1];section.querySelector('.material-index').textContent=`0${i+1} / 03`;section.querySelectorAll('.material-image').forEach((im,n)=>im.classList.toggle('active',i===n));document.querySelectorAll('[data-material]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});
 const saved=new Set();
 function renderSaved(){
  document.querySelectorAll('[data-save]').forEach(button=>{const on=saved.has(button.dataset.save);button.setAttribute('aria-pressed',String(on));button.innerHTML=`${on?'Feeling saved':'Save this feeling'} <span>${on?'♥':'♡'}</span>`});
  document.querySelectorAll('[data-edit]').forEach(button=>button.classList.toggle('saved',saved.has(button.dataset.edit)));
  document.getElementById('edit-intro').textContent=saved.size?`${saved.size} ${saved.size===1?'feeling':'feelings'} saved. Your own little collection.`:'A few possibilities to play with. Tap a photograph.';
  document.getElementById('edit-summary').textContent=saved.size?[...saved].map(s=>({living:'TOGETHER',kitchen:'DISCOVERY',office:'STILLNESS'})[s]).join(' + '):'YOUR PERSPECTIVE STARTS HERE.';
 }
 document.querySelectorAll('[data-save]').forEach(button=>button.onclick=()=>{const name=button.dataset.save;saved.has(name)?saved.delete(name):saved.add(name);renderSaved()});
 let active=1;
 function bringToFront(i){active=i;document.querySelectorAll('[data-edit]').forEach((el,n)=>{el.classList.toggle('on-top',i===n);el.setAttribute('aria-pressed',String(i===n))});}
 document.querySelectorAll('[data-edit]').forEach((button,i)=>button.onclick=()=>bringToFront(i));
 document.getElementById('shuffle-board').onclick=()=>bringToFront((active+1)%3);
}
